### PR TITLE
Options Menu

### PR DESCRIPTION
**Pull request by CeliaDawn**
Updated the strings in the options menu and added the custom frames

Text speed now properly goes "Slow -> Slower -> Slowest"

### CODE REVIEW

**Comment by CeliaDawn** [comment]
I hard-changed the text speeds. If this ever comes up again, it may be wise to manually change the variable names for TEXT_SPEED_SLOW, MID, and FAST into SLOW, SLOWER, and SLOWEST.

Presently, TEXT_SPEED_SLOW is the fastest.

**Comment by zx96** [comment]
Looks like this builds on top of #12 right now; I'm going to avoid looking at this until we get that merged or rebase this so there aren't 2,382 files changed... 😅

**Comment by jogaklaa** [comment]
> Looks like this builds on top of #12 right now; I'm going to avoid looking at this until we get that merged or rebase this so there aren't 2,382 files changed... 😅

exactly why I went ahead and made that pr. I'm pretty sure it's just assets being added there but would be good to have @CeliaDawn verify that

**Review by Sphyralg — APPROVED** [review]

**Comment by jogaklaa** [comment]
works on my machine

**Review by jogaklaa — APPROVED** [review]

**Pull request merged**
